### ISSUE TITLE
Broken link for Object tracking under Image processing heading

### ISSUE THREAD

**Issue by therc01** [neomatrix369/awesome-ai-ml-dl#105]
`https://github.com/virgili0/Virgilio/blob/master/serving/inferno/computer-vision/object-tracking/object-tracking.ipynb`  is giving error no. 404, under heading Image Processing under Computer Vision in /details/julia-python-and-r.md

**Comment by neomatrix369** [comment]
See **Object tracking** under https://github.com/neomatrix369/awesome-ai-ml-dl/blob/master/details/julia-python-and-r.md#image-processing, it should be fixed.

**Comment by neomatrix369** [comment]
Please also take a look at this to help find and fix many such links https://github.com/neomatrix369/awesome-ai-ml-dl/issues/54
