### ISSUE TITLE
Need for adding Computer Vision topic under Julia, Python and R 

### ISSUE THREAD

**Issue by jerryfrancis-97** [neomatrix369/awesome-ai-ml-dl#27]
Computer vision topic should focus on the basics of image processing , different filters used, and will then move onto CNNs and deep learning methods of computer vision.

**Comment by jerryfrancis-97** [comment]
Can I work on this issue as part of the hacktoberfest challenge?

**Comment by neomatrix369** [comment]
I have tagged it as a #Hacktoberfest issue, please go ahead! Waiting for your PR!

**Comment by neomatrix369** [comment]
Have you implemented all of the ideas under this issue, if so, please close this issue or else continue creating PRs under it!
