### ISSUE TITLE
Wolfram Neural Net Repository

### ISSUE THREAD

**Issue by arnoudbuzing** [neomatrix369/awesome-ai-ml-dl#32]
Probably a useful link to add to this repo (under Mathematica / Wolfram Language):

https://resources.wolframcloud.com/NeuralNetRepository/

The Wolfram Neural Net Repository is a public resource that hosts an expanding collection of trained and untrained neural network models, suitable for immediate evaluation, training, visualization, transfer learning and more.

**Comment by arnoudbuzing** [comment]
Additionally, this is a good overview page of Neural Network functions available in Mathematica / Wolfram Language:

https://reference.wolfram.com/language/guide/NeuralNetworks.html

And the main introduction on how to program with neural networks in Mathematica / Wolfram Language: 

https://reference.wolfram.com/language/tutorial/NeuralNetworksIntroduction.html

**Comment by neomatrix369** [comment]
Thanks @arnoudbuzing  pls feel free to create a PR for changes to the respective places - if you signup to the Hacktoberfest you will even get points for your efforts, see details on https://hacktoberfest.digitalocean.com

**Comment by neomatrix369** [comment]
Sorry about that, I have removed the name of the file. Can you pls rebase please?

**Comment by arnoudbuzing** [comment]
ok, I've added the pull request:

https://github.com/neomatrix369/awesome-ai-ml-dl/pull/34

**Comment by neomatrix369** [comment]
@arnoudbuzing I added the narrations to the page, see 4f14184ac765c9d031b1ea57976916dbdc93495c, also removed a duplicate link and added the link you might have missed

Let me know if you are happy with this?

Is this issue good to close? Do let me know.

**Comment by arnoudbuzing** [comment]
Looks good to me!
