### ISSUE TITLE
Link to 'topic-wise notes: math and stats' is missing(to be updated).

### ISSUE THREAD

**Issue by pvsharshith** [neomatrix369/awesome-ai-ml-dl#53]
The link to "topic-wise notes: math and stats"(ctanujit.org/notes.html) in 'Mathematics, Statistics, Probability & Probabilistic programming' section of README.md has to be updated as it's leading to '404: Page not found' error currently.

**Comment by pvsharshith** [comment]
I guess the proper link is https://www.ctanujit.org/lecture-notes.html , but I'm not sure. So please review it!

**Comment by neomatrix369** [comment]
Thanks @pvsharshith for raising this issue! It has been fixed now as you can see from the commit on this issue!
