### ISSUE TITLE
Due to incompatibility between spacy and pytextrank, we are unable to generate a summary

### ISSUE THREAD

**Issue by sagar98cyber** [neomatrix369/awesome-ai-ml-dl#61]
![image](https://user-images.githubusercontent.com/57261622/76139596-865f7900-6077-11ea-8e7d-1956d9e03e31.png)

**Comment by neomatrix369** [comment]
@sagar98cyber I have had this bug as well and so supplied a workaround, and even after that when it does not work we get this issue. 

Let me see what I can do about it.

Are you running this on Google Colab, Kaggle or on your local Jupyter instance or from inside the docker container (Better NLP on Docker Hub) - can you please let me know.

**Comment by neomatrix369** [comment]
Thanks for reporting this issue, it seems the `pytextrank` and `spacy` issues are resolved, I will soon push the fix and update all notebooks, please hold off for some time in the meanwhile.

**Comment by neomatrix369** [comment]
Fixed by @8329ada

**Comment by neomatrix369** [comment]
@sagar98cyber can you please take a look at the notebook again and see if everything works for you now?
