### ISSUE TITLE
Add Dataiku Community link to learning ressources

### ISSUE THREAD

**Issue by claudiush** [neomatrix369/awesome-ai-ml-dl#62]
I am super biased here, but I suggest you could add https://community.dataiku.com as well to the learning ressources 😀

**Comment by neomatrix369** [comment]
@claudiush Please feel free to add this via a Pull request. 

Also, there might be some sub-links under the community category - would be great to have them included as well. ;)

**Comment by neomatrix369** [comment]
Added link via e10a1d7c6c4d118ee5dd7fde9cd0ed122580c59c

**Comment by neomatrix369** [comment]
Thanks @claudiush its done now. Please feel free to share this page with your team and rest of the community and also share back-links into this page to enhance it.
