### ISSUE TITLE
Why to add "Tutorial" in names of R articles added?

### ISSUE THREAD

**Issue by dA505819** [neomatrix369/awesome-ai-ml-dl#76]
Articles are self explanatory from their headings. I feel adding tutorial specifically under R subsection is somewhat should not be there. 

Just like other good articles by great authors, their heading should be kept unchanged.

**Comment by neomatrix369** [comment]
@dA505819 good point, have you managed to do this for all the links so far?

Any PR related to this link?

**Comment by dA505819** [comment]
@neomatrix369 I will restructure it and will generate a PR.

**Comment by dA505819** [comment]
@neomatrix369 Linking Pull Request #77. Please check.

**Comment by neomatrix369** [comment]
Thanks, closing issue then!

**Comment by dA505819** [comment]
@neomatrix369 Allright!
