### ISSUE TITLE
Fixing Dead Links in Guides

### ISSUE THREAD

**Issue by ShambhaviCodes** [neomatrix369/awesome-ai-ml-dl#79]
As in #54 I would like to work on the broken links in the Guides Section.

**Comment by neomatrix369** [comment]
@ShambhaviCodes you may needed these two links:
- https://virgili0.github.io/Virgilio/
- https://github.com/virgili0/Virgilio

Feel free to use links from either of the sources to fix the guides related links. Let me know when to start as I have this on my list as to fix
