### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by tjj225** [neomatrix369/awesome-ai-ml-dl#84]
Reached this awesome list from the : akullpp/awesome-java . 

https://github.com/neomatrix369/awesome-ai-ml-dl/blob/master/details/java-jvm.md#java

Using Java for Artificial Intelligence (Tweet)

This link is broken. 

Thank you!

**Comment by neomatrix369** [comment]
> Reached this awesome list from the : akullpp/awesome-java .
> 
> https://github.com/neomatrix369/awesome-ai-ml-dl/blob/master/details/java-jvm.md#java
> 
> Using Java for Artificial Intelligence (Tweet)
> 
> This link is broken.
> 
> Thank you!

I don't follow this issue, how is this link broken, it takes me to the Java/JVM page: what were you expecting to see?

![image](https://user-images.githubusercontent.com/1570917/93779440-e639fd80-fc1e-11ea-9aea-b3d17d4527f1.png)


>This link is broken.

Can you please post the link that is not working?

**Comment by neomatrix369** [comment]
> [Using Java for Artificial Intelligence (Tweet)](https://skymind.ai/wiki/java-ai)
If you are referring to Skymind.ai, they have closed that link, thanks for reporting but these things happen, I'm not sure what alternative link I can replace it with

**Comment by neomatrix369** [comment]
Closed via 1e9b18f

**Comment by neomatrix369** [comment]
@tjj225 I have an issue dedicated to fixing broken links, see #82. Please take a look at it if you like to help with a PR - it's all explained there
